# Generated by Django 3.0.1 on 2019-12-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
