# Generated by Django 3.0.1 on 2020-01-02 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedproject',
            name='project_link',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Project Link'),
            preserve_default=False,
        ),
    ]
