# Generated by Django 3.0.1 on 2020-01-02 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_completedproject_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedproject',
            name='project_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='Project Id'),
            preserve_default=False,
        ),
    ]
