# Generated by Django 3.0.1 on 2020-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_completedproject_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Certificate description')),
                ('image', models.ImageField(default='default.png', upload_to='certs')),
            ],
        ),
    ]
