# Generated by Django 3.0.1 on 2020-01-03 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='attachment_address',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Attachment Address'),
            preserve_default=False,
        ),
    ]
